#version 460

layout(set = 0, binding = 0, rgba16f) uniform writeonly image3D voxels;

layout(push_constant) uniform Constants {
    uint padding0;
    uint padding1;
    uint padding2;
    uint padding3;
    uint padding4;
    uint padding5;
    uint padding6;
    uint padding7;
} push_constants;

layout(local_size_x = 4, local_size_y = 4, local_size_z = 4) in;

void main() {
    ivec3 cell = ivec3(gl_GlobalInvocationID);
    imageStore(voxels, cell, vec4(0, 0, 0, 0));
}
